export type { FreteInput, FreteResultado, CustoDetalhado, Custos, Veredicto } from './types';
export { calcularFrete, FORMULA_VERSAO } from './calcularFrete';
export { calcularPisoANTT, ANTT_CARGA_GERAL, ANTT_VERSAO, ANTT_FONTE } from './pisoANTT';
export { fmtBRL, fmtPct, centsToReais, reaisToCents, parseNumeroPtBR } from './format';
export { caminhoes, marcas } from './caminhoes';
export type { ModeloCaminhao } from './caminhoes';
export { VEICULOS, CARROCERIAS, eixosPorCarroceria } from './tiposCaminhao';
export type { TipoVeiculo, TipoCarroceria } from './tiposCaminhao';
export { normalizarVeiculoExterno } from './compatibilidadeExterna';
export type { ResultadoNormalizacao } from './compatibilidadeExterna';
